# Generated by Django 4.1.7 on 2023-03-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_group_text', models.TextField(max_length=5000, verbose_name='О группе')),
                ('image_of_group', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_concert', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('concert_venue', models.CharField(max_length=1000, verbose_name='Место концерта')),
                ('date_concert', models.DateTimeField(verbose_name='Дата концерта')),
                ('image_concert', models.ImageField(upload_to='img_concert/%Y/%m/%d', verbose_name='Превью')),
                ('links', models.CharField(max_length=1000, verbose_name='Ссылки')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
