# Generated by Django 4.1.7 on 2023-03-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutgroup',
            options={'verbose_name': 'О группе', 'verbose_name_plural': 'О группе'},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['title_concert'], 'verbose_name': 'Концерты', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='concert_venue',
            new_name='concert_place',
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_city',
            field=models.CharField(default='default', max_length=1000, verbose_name='Город концерта'),
            preserve_default=False,
        ),
    ]
