# Generated by Django 4.1.7 on 2023-03-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0002_alter_aboutgroup_options_alter_concert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['title'], 'verbose_name': 'Концерты', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='concert_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='date_concert',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='image_concert',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='concert_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='title_concert',
            new_name='title',
        ),
    ]
