# Generated by Django 4.1.4 on 2023-03-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0004_group_delete_aboutgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='image',
        ),
    ]
