# Generated by Django 4.1.4 on 2023-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0006_clips_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clips',
            options={'verbose_name': 'Клипы', 'verbose_name_plural': 'Клипы'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='links',
            old_name='resource',
            new_name='resourse',
        ),
        migrations.AlterField(
            model_name='clips',
            name='link',
            field=models.CharField(max_length=300, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=300, unique=True, verbose_name='Ссылка'),
        ),
    ]
