# Generated by Django 4.1.4 on 2023-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0007_alter_clips_options_alter_links_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерты', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.RemoveField(
            model_name='concert',
            name='links',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='title',
        ),
        migrations.AddField(
            model_name='concert',
            name='link',
            field=models.CharField(default='empty', max_length=1000, verbose_name='Ссылка для покупки билета'),
            preserve_default=False,
        ),
    ]
