# Generated by Django 4.1.4 on 2023-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0008_alter_concert_options_remove_concert_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='link',
        ),
        migrations.AddField(
            model_name='concert',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AddField(
            model_name='concert',
            name='slug',
            field=models.SlugField(default='abc', max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
