# Generated by Django 4.1.4 on 2023-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0009_remove_concert_link_concert_count_concert_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('count_bilet', models.IntegerField()),
            ],
        ),
    ]
