# Generated by Django 4.1.4 on 2023-03-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0011_buyer_data_time_buy_alter_buyer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Покупателя', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='concert',
            field=models.CharField(default='empty', max_length=500, verbose_name='Концерт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='count_bilet',
            field=models.IntegerField(verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='data_time_buy',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Ваш Email'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
