# Generated by Django 4.1.4 on 2023-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0012_alter_buyer_options_buyer_concert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='concert',
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(default='empty', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='place',
            field=models.CharField(default='empty', max_length=100, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваш Email'),
        ),
    ]
