# Generated by Django 4.1.4 on 2023-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0013_remove_buyer_concert_buyer_city_buyer_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(default='1', max_length=5000, verbose_name='Фото поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='post_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(default='1', max_length=5000, verbose_name='Текст поста'),
            preserve_default=False,
        ),
    ]
