# Generated by Django 4.1.7 on 2023-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0015_alter_news_options_alter_clips_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='image',
            field=models.URLField(verbose_name='Сылка на превью'),
        ),
        migrations.AlterField(
            model_name='clips',
            name='link',
            field=models.CharField(max_length=300, unique=True, verbose_name='Сылка на видео'),
        ),
    ]
