# Generated by Django 4.1.7 on 2023-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewindgroup', '0018_buyer_price_concert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Кол-во билетов'),
        ),
    ]
